# AUTO-GENERATED by tools/glyphs.py — do not edit by hand.
# Stroke-path data for traceable glyphs. Coords normalized [0,1]x[0,1]
# (x right, y down). Each glyph = ordered Array of strokes;
# each stroke = PackedVector2Array of waypoints in draw order.
# Registered as the "Glyphs" autoload singleton.
extends Node

var STROKES: Dictionary = {}

func _ready() -> void:
	_build()

## Returns the ordered list of strokes (PackedVector2Array) for a glyph.
func get_strokes(glyph: String) -> Array:
	return STROKES.get(glyph, [])

func _build() -> void:
	STROKES = {
		"A": [
			PackedVector2Array([Vector2(0.1800, 0.9200), Vector2(0.5000, 0.0800)]),
			PackedVector2Array([Vector2(0.5000, 0.0800), Vector2(0.8200, 0.9200)]),
			PackedVector2Array([Vector2(0.3100, 0.6200), Vector2(0.6900, 0.6200)]),
		],
		"B": [
			PackedVector2Array([Vector2(0.2800, 0.0800), Vector2(0.2800, 0.9200)]),
			PackedVector2Array([Vector2(0.2800, 0.0800), Vector2(0.3385, 0.0840), Vector2(0.3948, 0.0960), Vector2(0.4467, 0.1154), Vector2(0.4921, 0.1415), Vector2(0.5294, 0.1733), Vector2(0.5572, 0.2096), Vector2(0.5742, 0.2490), Vector2(0.5800, 0.2900), Vector2(0.5742, 0.3310), Vector2(0.5572, 0.3704), Vector2(0.5294, 0.4067), Vector2(0.4921, 0.4385), Vector2(0.4467, 0.4646), Vector2(0.3948, 0.4840), Vector2(0.3385, 0.4960), Vector2(0.2800, 0.5000)]),
			PackedVector2Array([Vector2(0.2800, 0.5000), Vector2(0.3463, 0.5040), Vector2(0.4101, 0.5160), Vector2(0.4689, 0.5354), Vector2(0.5204, 0.5615), Vector2(0.5627, 0.5933), Vector2(0.5941, 0.6296), Vector2(0.6135, 0.6690), Vector2(0.6200, 0.7100), Vector2(0.6135, 0.7510), Vector2(0.5941, 0.7904), Vector2(0.5627, 0.8267), Vector2(0.5204, 0.8585), Vector2(0.4689, 0.8846), Vector2(0.4101, 0.9040), Vector2(0.3463, 0.9160), Vector2(0.2800, 0.9200)]),
		],
		"C": [
			PackedVector2Array([Vector2(0.7293, 0.1690), Vector2(0.6873, 0.1343), Vector2(0.6415, 0.1077), Vector2(0.5930, 0.0898), Vector2(0.5429, 0.0810), Vector2(0.4923, 0.0814), Vector2(0.4424, 0.0911), Vector2(0.3941, 0.1099), Vector2(0.3486, 0.1373), Vector2(0.3070, 0.1727), Vector2(0.2700, 0.2154), Vector2(0.2386, 0.2643), Vector2(0.2134, 0.3185), Vector2(0.1950, 0.3767), Vector2(0.1838, 0.4377), Vector2(0.1800, 0.5000), Vector2(0.1838, 0.5623), Vector2(0.1950, 0.6233), Vector2(0.2134, 0.6815), Vector2(0.2386, 0.7357), Vector2(0.2700, 0.7846), Vector2(0.3070, 0.8273), Vector2(0.3486, 0.8627), Vector2(0.3941, 0.8901), Vector2(0.4424, 0.9089), Vector2(0.4923, 0.9186), Vector2(0.5429, 0.9190), Vector2(0.5930, 0.9102), Vector2(0.6415, 0.8923), Vector2(0.6873, 0.8657), Vector2(0.7293, 0.8310)]),
		],
		"D": [
			PackedVector2Array([Vector2(0.2800, 0.0800), Vector2(0.2800, 0.9200)]),
			PackedVector2Array([Vector2(0.2800, 0.0800), Vector2(0.3453, 0.0836), Vector2(0.4094, 0.0943), Vector2(0.4713, 0.1120), Vector2(0.5300, 0.1363), Vector2(0.5844, 0.1668), Vector2(0.6336, 0.2030), Vector2(0.6767, 0.2443), Vector2(0.7130, 0.2900), Vector2(0.7419, 0.3393), Vector2(0.7630, 0.3913), Vector2(0.7757, 0.4452), Vector2(0.7800, 0.5000), Vector2(0.7757, 0.5548), Vector2(0.7630, 0.6087), Vector2(0.7419, 0.6607), Vector2(0.7130, 0.7100), Vector2(0.6767, 0.7557), Vector2(0.6336, 0.7970), Vector2(0.5844, 0.8332), Vector2(0.5300, 0.8637), Vector2(0.4713, 0.8880), Vector2(0.4094, 0.9057), Vector2(0.3453, 0.9164), Vector2(0.2800, 0.9200)]),
		],
		"E": [
			PackedVector2Array([Vector2(0.3000, 0.0800), Vector2(0.3000, 0.9200)]),
			PackedVector2Array([Vector2(0.3000, 0.0800), Vector2(0.7200, 0.0800)]),
			PackedVector2Array([Vector2(0.3000, 0.5000), Vector2(0.6600, 0.5000)]),
			PackedVector2Array([Vector2(0.3000, 0.9200), Vector2(0.7200, 0.9200)]),
		],
		"F": [
			PackedVector2Array([Vector2(0.3000, 0.0800), Vector2(0.3000, 0.9200)]),
			PackedVector2Array([Vector2(0.3000, 0.0800), Vector2(0.7200, 0.0800)]),
			PackedVector2Array([Vector2(0.3000, 0.5000), Vector2(0.6600, 0.5000)]),
		],
		"G": [
			PackedVector2Array([Vector2(0.7293, 0.1690), Vector2(0.6856, 0.1332), Vector2(0.6379, 0.1061), Vector2(0.5874, 0.0883), Vector2(0.5353, 0.0804), Vector2(0.4828, 0.0825), Vector2(0.4312, 0.0946), Vector2(0.3817, 0.1163), Vector2(0.3355, 0.1472), Vector2(0.2938, 0.1865), Vector2(0.2574, 0.2333), Vector2(0.2273, 0.2864), Vector2(0.2041, 0.3446), Vector2(0.1885, 0.4065), Vector2(0.1808, 0.4707), Vector2(0.1812, 0.5356), Vector2(0.1897, 0.5996), Vector2(0.2060, 0.6612), Vector2(0.2299, 0.7190), Vector2(0.2606, 0.7716), Vector2(0.2976, 0.8177), Vector2(0.3398, 0.8562), Vector2(0.3864, 0.8862), Vector2(0.4361, 0.9070), Vector2(0.4878, 0.9181), Vector2(0.5403, 0.9192), Vector2(0.5923, 0.9104), Vector2(0.6426, 0.8917), Vector2(0.6900, 0.8637)]),
			PackedVector2Array([Vector2(0.7400, 0.5500), Vector2(0.5200, 0.5500)]),
		],
		"H": [
			PackedVector2Array([Vector2(0.2800, 0.0800), Vector2(0.2800, 0.9200)]),
			PackedVector2Array([Vector2(0.7200, 0.0800), Vector2(0.7200, 0.9200)]),
			PackedVector2Array([Vector2(0.2800, 0.5000), Vector2(0.7200, 0.5000)]),
		],
		"I": [
			PackedVector2Array([Vector2(0.3200, 0.0800), Vector2(0.6800, 0.0800)]),
			PackedVector2Array([Vector2(0.5000, 0.0800), Vector2(0.5000, 0.9200)]),
			PackedVector2Array([Vector2(0.3200, 0.9200), Vector2(0.6800, 0.9200)]),
		],
		"J": [
			PackedVector2Array([Vector2(0.6200, 0.0800), Vector2(0.6200, 0.6600), Vector2(0.6160, 0.7045), Vector2(0.6042, 0.7468), Vector2(0.5851, 0.7847), Vector2(0.5598, 0.8164), Vector2(0.5294, 0.8402), Vector2(0.4956, 0.8550), Vector2(0.4600, 0.8600), Vector2(0.4244, 0.8550), Vector2(0.3906, 0.8402), Vector2(0.3602, 0.8164), Vector2(0.3349, 0.7847), Vector2(0.3158, 0.7468), Vector2(0.3040, 0.7045), Vector2(0.3000, 0.6600)]),
			PackedVector2Array([Vector2(0.4600, 0.0800), Vector2(0.7800, 0.0800)]),
		],
		"K": [
			PackedVector2Array([Vector2(0.3000, 0.0800), Vector2(0.3000, 0.9200)]),
			PackedVector2Array([Vector2(0.7200, 0.0800), Vector2(0.3000, 0.5200)]),
			PackedVector2Array([Vector2(0.3400, 0.4800), Vector2(0.7400, 0.9200)]),
		],
		"L": [
			PackedVector2Array([Vector2(0.3200, 0.0800), Vector2(0.3200, 0.9200), Vector2(0.7200, 0.9200)]),
		],
		"M": [
			PackedVector2Array([Vector2(0.2000, 0.9200), Vector2(0.2000, 0.0800), Vector2(0.5000, 0.6200), Vector2(0.8000, 0.0800), Vector2(0.8000, 0.9200)]),
		],
		"N": [
			PackedVector2Array([Vector2(0.2800, 0.9200), Vector2(0.2800, 0.0800), Vector2(0.7200, 0.9200), Vector2(0.7200, 0.0800)]),
		],
		"O": [
			PackedVector2Array([Vector2(0.5000, 0.0800), Vector2(0.4337, 0.0881), Vector2(0.3699, 0.1120), Vector2(0.3111, 0.1508), Vector2(0.2596, 0.2030), Vector2(0.2173, 0.2667), Vector2(0.1859, 0.3393), Vector2(0.1665, 0.4181), Vector2(0.1600, 0.5000), Vector2(0.1665, 0.5819), Vector2(0.1859, 0.6607), Vector2(0.2173, 0.7333), Vector2(0.2596, 0.7970), Vector2(0.3111, 0.8492), Vector2(0.3699, 0.8880), Vector2(0.4337, 0.9119), Vector2(0.5000, 0.9200), Vector2(0.5663, 0.9119), Vector2(0.6301, 0.8880), Vector2(0.6889, 0.8492), Vector2(0.7404, 0.7970), Vector2(0.7827, 0.7333), Vector2(0.8141, 0.6607), Vector2(0.8335, 0.5819), Vector2(0.8400, 0.5000), Vector2(0.8335, 0.4181), Vector2(0.8141, 0.3393), Vector2(0.7827, 0.2667), Vector2(0.7404, 0.2030), Vector2(0.6889, 0.1508), Vector2(0.6301, 0.1120), Vector2(0.5663, 0.0881), Vector2(0.5000, 0.0800)]),
		],
		"P": [
			PackedVector2Array([Vector2(0.2800, 0.0800), Vector2(0.2800, 0.9200)]),
			PackedVector2Array([Vector2(0.2800, 0.0800), Vector2(0.3424, 0.0840), Vector2(0.4025, 0.0960), Vector2(0.4578, 0.1154), Vector2(0.5063, 0.1415), Vector2(0.5461, 0.1733), Vector2(0.5756, 0.2096), Vector2(0.5939, 0.2490), Vector2(0.6000, 0.2900), Vector2(0.5939, 0.3310), Vector2(0.5756, 0.3704), Vector2(0.5461, 0.4067), Vector2(0.5063, 0.4385), Vector2(0.4578, 0.4646), Vector2(0.4025, 0.4840), Vector2(0.3424, 0.4960), Vector2(0.2800, 0.5000)]),
		],
		"Q": [
			PackedVector2Array([Vector2(0.5000, 0.0800), Vector2(0.4337, 0.0881), Vector2(0.3699, 0.1120), Vector2(0.3111, 0.1508), Vector2(0.2596, 0.2030), Vector2(0.2173, 0.2667), Vector2(0.1859, 0.3393), Vector2(0.1665, 0.4181), Vector2(0.1600, 0.5000), Vector2(0.1665, 0.5819), Vector2(0.1859, 0.6607), Vector2(0.2173, 0.7333), Vector2(0.2596, 0.7970), Vector2(0.3111, 0.8492), Vector2(0.3699, 0.8880), Vector2(0.4337, 0.9119), Vector2(0.5000, 0.9200), Vector2(0.5663, 0.9119), Vector2(0.6301, 0.8880), Vector2(0.6889, 0.8492), Vector2(0.7404, 0.7970), Vector2(0.7827, 0.7333), Vector2(0.8141, 0.6607), Vector2(0.8335, 0.5819), Vector2(0.8400, 0.5000), Vector2(0.8335, 0.4181), Vector2(0.8141, 0.3393), Vector2(0.7827, 0.2667), Vector2(0.7404, 0.2030), Vector2(0.6889, 0.1508), Vector2(0.6301, 0.1120), Vector2(0.5663, 0.0881), Vector2(0.5000, 0.0800)]),
			PackedVector2Array([Vector2(0.5800, 0.6200), Vector2(0.8400, 0.9400)]),
		],
		"R": [
			PackedVector2Array([Vector2(0.2800, 0.0800), Vector2(0.2800, 0.9200)]),
			PackedVector2Array([Vector2(0.2800, 0.0800), Vector2(0.3424, 0.0840), Vector2(0.4025, 0.0960), Vector2(0.4578, 0.1154), Vector2(0.5063, 0.1415), Vector2(0.5461, 0.1733), Vector2(0.5756, 0.2096), Vector2(0.5939, 0.2490), Vector2(0.6000, 0.2900), Vector2(0.5939, 0.3310), Vector2(0.5756, 0.3704), Vector2(0.5461, 0.4067), Vector2(0.5063, 0.4385), Vector2(0.4578, 0.4646), Vector2(0.4025, 0.4840), Vector2(0.3424, 0.4960), Vector2(0.2800, 0.5000)]),
			PackedVector2Array([Vector2(0.2800, 0.5000), Vector2(0.7400, 0.9200)]),
		],
		"S": [
			PackedVector2Array([Vector2(0.6905, 0.1900), Vector2(0.6685, 0.1586), Vector2(0.6414, 0.1315), Vector2(0.6100, 0.1095), Vector2(0.5752, 0.0933), Vector2(0.5382, 0.0833), Vector2(0.5000, 0.0800), Vector2(0.4618, 0.0833), Vector2(0.4248, 0.0933), Vector2(0.3900, 0.1095), Vector2(0.3586, 0.1315), Vector2(0.3315, 0.1586), Vector2(0.3095, 0.1900), Vector2(0.2933, 0.2248), Vector2(0.2833, 0.2618), Vector2(0.2800, 0.3000), Vector2(0.2833, 0.3382), Vector2(0.2933, 0.3752), Vector2(0.3095, 0.4100), Vector2(0.6905, 0.5900), Vector2(0.7067, 0.6248), Vector2(0.7167, 0.6618), Vector2(0.7200, 0.7000), Vector2(0.7167, 0.7382), Vector2(0.7067, 0.7752), Vector2(0.6905, 0.8100), Vector2(0.6685, 0.8414), Vector2(0.6414, 0.8685), Vector2(0.6100, 0.8905), Vector2(0.5752, 0.9067), Vector2(0.5382, 0.9167), Vector2(0.5000, 0.9200), Vector2(0.4618, 0.9167), Vector2(0.4248, 0.9067), Vector2(0.3900, 0.8905), Vector2(0.3586, 0.8685), Vector2(0.3315, 0.8414), Vector2(0.3095, 0.8100)]),
		],
		"T": [
			PackedVector2Array([Vector2(0.2000, 0.0800), Vector2(0.8000, 0.0800)]),
			PackedVector2Array([Vector2(0.5000, 0.0800), Vector2(0.5000, 0.9200)]),
		],
		"U": [
			PackedVector2Array([Vector2(0.2800, 0.0800), Vector2(0.2800, 0.6000), Vector2(0.2833, 0.6556), Vector2(0.2933, 0.7094), Vector2(0.3095, 0.7600), Vector2(0.3315, 0.8057), Vector2(0.3586, 0.8451), Vector2(0.3900, 0.8771), Vector2(0.4248, 0.9007), Vector2(0.4618, 0.9151), Vector2(0.5000, 0.9200), Vector2(0.5382, 0.9151), Vector2(0.5752, 0.9007), Vector2(0.6100, 0.8771), Vector2(0.6414, 0.8451), Vector2(0.6685, 0.8057), Vector2(0.6905, 0.7600), Vector2(0.7067, 0.7094), Vector2(0.7167, 0.6556), Vector2(0.7200, 0.6000), Vector2(0.7200, 0.0800)]),
		],
		"V": [
			PackedVector2Array([Vector2(0.2200, 0.0800), Vector2(0.5000, 0.9200), Vector2(0.7800, 0.0800)]),
		],
		"W": [
			PackedVector2Array([Vector2(0.1400, 0.0800), Vector2(0.3200, 0.9200), Vector2(0.5000, 0.3200), Vector2(0.6800, 0.9200), Vector2(0.8600, 0.0800)]),
		],
		"X": [
			PackedVector2Array([Vector2(0.2800, 0.0800), Vector2(0.7200, 0.9200)]),
			PackedVector2Array([Vector2(0.7200, 0.0800), Vector2(0.2800, 0.9200)]),
		],
		"Y": [
			PackedVector2Array([Vector2(0.2800, 0.0800), Vector2(0.5000, 0.5000)]),
			PackedVector2Array([Vector2(0.7200, 0.0800), Vector2(0.5000, 0.5000)]),
			PackedVector2Array([Vector2(0.5000, 0.5000), Vector2(0.5000, 0.9200)]),
		],
		"Z": [
			PackedVector2Array([Vector2(0.2800, 0.0800), Vector2(0.7200, 0.0800), Vector2(0.2800, 0.9200), Vector2(0.7200, 0.9200)]),
		],
		"0": [
			PackedVector2Array([Vector2(0.5000, 0.0800), Vector2(0.4454, 0.0881), Vector2(0.3928, 0.1120), Vector2(0.3444, 0.1508), Vector2(0.3020, 0.2030), Vector2(0.2672, 0.2667), Vector2(0.2413, 0.3393), Vector2(0.2254, 0.4181), Vector2(0.2200, 0.5000), Vector2(0.2254, 0.5819), Vector2(0.2413, 0.6607), Vector2(0.2672, 0.7333), Vector2(0.3020, 0.7970), Vector2(0.3444, 0.8492), Vector2(0.3928, 0.8880), Vector2(0.4454, 0.9119), Vector2(0.5000, 0.9200), Vector2(0.5546, 0.9119), Vector2(0.6072, 0.8880), Vector2(0.6556, 0.8492), Vector2(0.6980, 0.7970), Vector2(0.7328, 0.7333), Vector2(0.7587, 0.6607), Vector2(0.7746, 0.5819), Vector2(0.7800, 0.5000), Vector2(0.7746, 0.4181), Vector2(0.7587, 0.3393), Vector2(0.7328, 0.2667), Vector2(0.6980, 0.2030), Vector2(0.6556, 0.1508), Vector2(0.6072, 0.1120), Vector2(0.5546, 0.0881), Vector2(0.5000, 0.0800)]),
		],
		"1": [
			PackedVector2Array([Vector2(0.3400, 0.2400), Vector2(0.5000, 0.0800), Vector2(0.5000, 0.9200)]),
			PackedVector2Array([Vector2(0.3200, 0.9200), Vector2(0.6800, 0.9200)]),
		],
		"2": [
			PackedVector2Array([Vector2(0.2885, 0.2521), Vector2(0.3038, 0.2150), Vector2(0.3261, 0.1814), Vector2(0.3547, 0.1523), Vector2(0.3885, 0.1290), Vector2(0.4264, 0.1121), Vector2(0.4668, 0.1024), Vector2(0.5085, 0.1002), Vector2(0.5499, 0.1055), Vector2(0.5895, 0.1182), Vector2(0.6258, 0.1377), Vector2(0.6577, 0.1635), Vector2(0.6838, 0.1946), Vector2(0.7033, 0.2298), Vector2(0.7155, 0.2679), Vector2(0.7200, 0.3076), Vector2(0.7165, 0.3473), Vector2(0.7052, 0.3856), Vector2(0.6866, 0.4213), Vector2(0.6900, 0.4200), Vector2(0.3000, 0.8500), Vector2(0.3000, 0.9000), Vector2(0.7400, 0.9000)]),
		],
		"3": [
			PackedVector2Array([Vector2(0.2845, 0.1569), Vector2(0.3258, 0.1187), Vector2(0.3765, 0.0927), Vector2(0.4326, 0.0807), Vector2(0.4901, 0.0837), Vector2(0.5445, 0.1014), Vector2(0.5919, 0.1325), Vector2(0.6286, 0.1748), Vector2(0.6519, 0.2249), Vector2(0.6600, 0.2791), Vector2(0.6524, 0.3334), Vector2(0.6295, 0.3838), Vector2(0.5932, 0.4263), Vector2(0.5462, 0.4578), Vector2(0.4919, 0.4760), Vector2(0.4344, 0.4795), Vector2(0.3782, 0.4679), Vector2(0.3645, 0.4351), Vector2(0.4162, 0.4223), Vector2(0.4694, 0.4208), Vector2(0.5217, 0.4305), Vector2(0.5708, 0.4511), Vector2(0.6144, 0.4816), Vector2(0.6505, 0.5207), Vector2(0.6776, 0.5665), Vector2(0.6943, 0.6171), Vector2(0.7000, 0.6700), Vector2(0.6943, 0.7229), Vector2(0.6776, 0.7735), Vector2(0.6505, 0.8193), Vector2(0.6144, 0.8584), Vector2(0.5708, 0.8889), Vector2(0.5217, 0.9095), Vector2(0.4694, 0.9192), Vector2(0.4162, 0.9177), Vector2(0.3645, 0.9049)]),
		],
		"4": [
			PackedVector2Array([Vector2(0.6200, 0.1000), Vector2(0.2400, 0.6400), Vector2(0.7800, 0.6400)]),
			PackedVector2Array([Vector2(0.6200, 0.1000), Vector2(0.6200, 0.9200)]),
		],
		"5": [
			PackedVector2Array([Vector2(0.6600, 0.1000), Vector2(0.3400, 0.1000), Vector2(0.3400, 0.4400)]),
			PackedVector2Array([Vector2(0.3242, 0.4157), Vector2(0.3848, 0.4021), Vector2(0.4471, 0.4012), Vector2(0.5081, 0.4132), Vector2(0.5647, 0.4374), Vector2(0.6141, 0.4726), Vector2(0.6539, 0.5171), Vector2(0.6822, 0.5687), Vector2(0.6974, 0.6248), Vector2(0.6989, 0.6827), Vector2(0.6866, 0.7394), Vector2(0.6611, 0.7922), Vector2(0.6237, 0.8384), Vector2(0.5761, 0.8758), Vector2(0.5208, 0.9025), Vector2(0.4606, 0.9173), Vector2(0.3983, 0.9192), Vector2(0.3371, 0.9083), Vector2(0.2800, 0.8852)]),
		],
		"6": [
			PackedVector2Array([Vector2(0.7192, 0.1800), Vector2(0.6871, 0.1455), Vector2(0.6500, 0.1175), Vector2(0.6089, 0.0969), Vector2(0.5651, 0.0843), Vector2(0.5200, 0.0800), Vector2(0.4749, 0.0843), Vector2(0.4311, 0.0969), Vector2(0.3900, 0.1175), Vector2(0.3529, 0.1455), Vector2(0.3208, 0.1800), Vector2(0.2948, 0.2200), Vector2(0.2757, 0.2642), Vector2(0.2639, 0.3114), Vector2(0.2600, 0.3600), Vector2(0.2639, 0.4086), Vector2(0.2757, 0.4558), Vector2(0.2600, 0.3600), Vector2(0.2600, 0.6600), Vector2(0.2670, 0.5978), Vector2(0.2875, 0.5392), Vector2(0.3204, 0.4876), Vector2(0.3637, 0.4460), Vector2(0.4149, 0.4169), Vector2(0.4711, 0.4019), Vector2(0.5289, 0.4019), Vector2(0.5851, 0.4169), Vector2(0.6363, 0.4460), Vector2(0.6796, 0.4876), Vector2(0.7125, 0.5392), Vector2(0.7330, 0.5978), Vector2(0.7400, 0.6600), Vector2(0.7330, 0.7222), Vector2(0.7125, 0.7808), Vector2(0.6796, 0.8324), Vector2(0.6363, 0.8740), Vector2(0.5851, 0.9031), Vector2(0.5289, 0.9181), Vector2(0.4711, 0.9181), Vector2(0.4149, 0.9031), Vector2(0.3637, 0.8740), Vector2(0.3204, 0.8324), Vector2(0.2875, 0.7808), Vector2(0.2670, 0.7222), Vector2(0.2600, 0.6600)]),
		],
		"7": [
			PackedVector2Array([Vector2(0.2600, 0.1000), Vector2(0.7600, 0.1000), Vector2(0.4200, 0.9200)]),
		],
		"8": [
			PackedVector2Array([Vector2(0.5000, 0.0800), Vector2(0.5684, 0.0933), Vector2(0.6286, 0.1315), Vector2(0.6732, 0.1900), Vector2(0.6970, 0.2618), Vector2(0.6970, 0.3382), Vector2(0.6732, 0.4100), Vector2(0.6286, 0.4685), Vector2(0.5684, 0.5067), Vector2(0.5000, 0.5200), Vector2(0.4316, 0.5067), Vector2(0.3714, 0.4685), Vector2(0.3268, 0.4100), Vector2(0.3030, 0.3382), Vector2(0.3030, 0.2618), Vector2(0.3268, 0.1900), Vector2(0.3714, 0.1315), Vector2(0.4316, 0.0933), Vector2(0.5000, 0.0800), Vector2(0.5000, 0.4600), Vector2(0.4324, 0.4697), Vector2(0.3702, 0.4981), Vector2(0.3186, 0.5428), Vector2(0.2817, 0.6003), Vector2(0.2624, 0.6658), Vector2(0.2624, 0.7342), Vector2(0.2817, 0.7997), Vector2(0.3186, 0.8572), Vector2(0.3702, 0.9019), Vector2(0.4324, 0.9303), Vector2(0.5000, 0.9400), Vector2(0.5676, 0.9303), Vector2(0.6298, 0.9019), Vector2(0.6814, 0.8572), Vector2(0.7183, 0.7997), Vector2(0.7376, 0.7342), Vector2(0.7376, 0.6658), Vector2(0.7183, 0.6003), Vector2(0.6814, 0.5428), Vector2(0.6298, 0.4981), Vector2(0.5676, 0.4697), Vector2(0.5000, 0.4600)]),
		],
		"9": [
			PackedVector2Array([Vector2(0.5000, 0.1000), Vector2(0.4380, 0.1097), Vector2(0.3811, 0.1381), Vector2(0.3337, 0.1828), Vector2(0.2999, 0.2403), Vector2(0.2822, 0.3058), Vector2(0.2822, 0.3742), Vector2(0.2999, 0.4397), Vector2(0.3337, 0.4972), Vector2(0.3811, 0.5419), Vector2(0.4380, 0.5703), Vector2(0.5000, 0.5800), Vector2(0.5620, 0.5703), Vector2(0.6189, 0.5419), Vector2(0.6663, 0.4972), Vector2(0.7001, 0.4397), Vector2(0.7178, 0.3742), Vector2(0.7178, 0.3058), Vector2(0.7001, 0.2403), Vector2(0.6663, 0.1828), Vector2(0.6189, 0.1381), Vector2(0.5620, 0.1097), Vector2(0.5000, 0.1000), Vector2(0.7200, 0.3400), Vector2(0.5000, 0.9200)]),
		],
	}
